export const Images = {
  Main_Logo_Light_IMG: require("../assets/imges/Maryasal-icon.jpg"),
  Main_Logo_Dark_IMG: require("../assets/imges/Maryasal-icon.png"),
  Typing_IMG: require("../assets/imges/bg-cta.jpg"),
  Table_IMG: require("../assets/imges/bg-hero.jpg"),
  LaDy_IMG: require("../assets/imges/blog-author.jpg"),
  BackGround_IMG: require("../assets/imges/experience-figure.png"),
  Chat_IMG: require("../assets/imges/favicon.png"),
  WOO_Commerce_IMG: require("../assets/imges/icon-woo.png"),
  WordPress_IMG: require("../assets/imges/icon-wp.png"),
  Logo_Full_IMG: require("../assets/imges/logoName.jpeg"),
  Map_IMG: require("../assets/imges/map.png"),
  Screen1_IMG: require("../assets/imges/portfolio-apple.jpeg"),
  Screen2_IMG: require("../assets/imges/portfolio-fedex.jpeg"),
  Screen3_IMG: require("../assets/imges/portfolio-microsoft.jpeg"),
  Screen4_IMG: require("../assets/imges/portfolio-stripe.jpeg"),
  Tree_IMG: require("../assets/imges/post-01.png"),
  Light_IMG: require("../assets/imges/post-02.png"),
  Bich_IMG: require("../assets/imges/post-03.png"),
  ATOM_IMG: require("../assets/imges/social.jpg"),
};
